#include <ncurses.h>

int main() {
    initscr();

    /* can the terminal output color text? */
    if (!has_colors()) {
        endwin();
        puts("Ncurses reports colors unavailable");
        return (1);
    }

    /* initialize Ncurses colors */
    if (start_color() != OK) {
        endwin();
        puts("Unable to start Ncurses color text");
        return (1);
    }

    /* report color text stats */
    /* COLORS represents the number of possibel colors
       that can be generated by the terminal */
    printw("Ncurses reports %d colors available\n", COLORS);
    /* COLOR_PAIRS are the number of color combinations,
       background and foreground, possible */
    printw("and up to %d color pairs.", COLOR_PAIRS);
    refresh();
    getch();

    endwin();

    return (0);
}
